# Generated by Django 2.2.24 on 2021-08-01 22:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210801_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 22, 40, 22, 918469, tzinfo=utc)),
        ),
    ]
