# Generated by Django 2.2.24 on 2021-08-02 01:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210801_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 1, 54, 54, 978355, tzinfo=utc)),
        ),
    ]
